-- ============================================================
-- Migration 052 : Jump lanes RSI officiels (ARK Starmap API)
-- Remplace les 29 lanes approximatifs du seed 013 par
-- 58 connexions validées depuis les 37 systèmes de la carte.
-- Nouveaux systèmes : Baker, Banshee, Caliban, Cano, Cathcart,
--   Croshaw, Ferron, Garron, Hadrian, Kellog, Kilian, Min, Sol,
--   Tanga, Tiber
-- ============================================================

DELETE FROM public.map_jump_lanes;

INSERT INTO public.map_jump_lanes (system_a, system_b) VALUES
  ('Ariel',    'Tamsa'),
  ('Baker',    'Kiel'),
  ('Baker',    'Terra'),
  ('Banshee',  'Garron'),
  ('Banshee',  'Leir'),
  ('Banshee',  'Tamsa'),
  ('Bremen',   'Nyx'),
  ('Bremen',   'Tanga'),
  ('Bremen',   'Vega'),
  ('Caliban',  'Nul'),
  ('Caliban',  'Oberon'),
  ('Caliban',  'Tiber'),
  ('Cano',     'Davien'),
  ('Cano',     'Pyro'),
  ('Castra',   'Nyx'),
  ('Castra',   'Pyro'),
  ('Cathcart', 'Davien'),
  ('Cathcart', 'Hades'),
  ('Cathcart', 'Kilian'),
  ('Cathcart', 'Nexus'),
  ('Chronos',  'Kellog'),
  ('Chronos',  'Vega'),
  ('Croshaw',  'Ferron'),
  ('Croshaw',  'Nul'),
  ('Croshaw',  'Sol'),
  ('Davien',   'Ferron'),
  ('Davien',   'Kilian'),
  ('Davien',   'Sol'),
  ('Ellis',    'Kilian'),
  ('Ellis',    'Magnus'),
  ('Ellis',    'Min'),
  ('Ellis',    'Nexus'),
  ('Ferron',   'Idris'),
  ('Garron',   'Idris'),
  ('Garron',   'Leir'),
  ('Hadrian',  'Kiel'),
  ('Hadrian',  'Pyro'),
  ('Hadrian',  'Terra'),
  ('Hades',    'Nexus'),
  ('Kellog',   'Odin'),
  ('Kellog',   'Tanga'),
  ('Kellog',   'Virgil'),
  ('Magnus',   'Stanton'),
  ('Magnus',   'Terra'),
  ('Min',      'Nexus'),
  ('Nul',      'Oberon'),
  ('Nyx',      'Odin'),
  ('Nyx',      'Pyro'),
  ('Nyx',      'Stanton'),
  ('Oberon',   'Tiber'),
  ('Oberon',   'Vega'),
  ('Oberon',   'Virgil'),
  ('Odin',     'Tanga'),
  ('Pyro',     'Stanton'),
  ('Pyro',     'Terra'),
  ('Stanton',  'Terra'),
  ('Tiber',    'Virgil'),
  ('Vega',     'Virgil')
ON CONFLICT DO NOTHING;
